version: '3.8'

## define database service
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: snuggles3
    ports:
      - "5432:5432"
